blueprint:
  name: Easy presence lights
  description: >
    Controls lights based on an mmWave sensor, with dual manual overrides and a sunset-to-sunrise time window.
  domain: automation

  input:
    presence_sensor:
      name: Presence Sensor
      selector:
        entity:
          domain: sensor

    target_lights:
      name: Lights (multi-select)
      selector:
        entity:
          domain: light
          multiple: true

    off_delay:
      name: Auto-off delay (seconds)
      default: 30
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: seconds

    manual_on_override_flag:
      name: Manual ON Override Boolean Helper
      selector:
        entity:
          domain: input_boolean

    manual_off_override_flag:
      name: Manual OFF Override Boolean Helper
      selector:
        entity:
          domain: input_boolean

    manual_on_minutes:
      name: Manual ON Override Duration (minutes)
      default: 5
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes

    manual_off_minutes:
      name: Manual OFF Override Duration (minutes)
      default: 10
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: minutes

    disable_sensors:
      name: Optional Disable Sensors
      description: If any of these sensors are ON, automation is disabled.
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    sunset_offset:
      name: Sunset Offset (minutes)
      description: Offset the start of the time window. Use a negative number to start before sunset.
      default: 0
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes

    sunrise_offset:
      name: Sunrise Offset (minutes)
      description: Offset the end of the time window. Use a positive number to end after sunrise.
      default: 0
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes

trigger:
  - platform: state
    entity_id: !input presence_sensor
  - platform: state
    entity_id: !input target_lights

condition:
  - condition: sun
    after: sunset
    after_offset: !input sunset_offset
    before: sunrise
    before_offset: !input sunrise_offset

action:
  - variables:
      sensor: !input presence_sensor
      lights: !input target_lights
      off_delay: !input off_delay
      on_flag: !input manual_on_override_flag
      off_flag: !input manual_off_override_flag
      on_minutes: !input manual_on_minutes
      off_minutes: !input manual_off_minutes
      disable_sensors: !input disable_sensors
      active_states: ["occupied"]

  ###########################################################################
  # 1 — Optional disable sensors
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ disable_sensors | length > 0 and (disable_sensors | select('is_state', 'on') | list | length > 0) }}
        sequence:
          - stop:

  ###########################################################################
  # 2 — Manual ON override
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id in lights
                 and trigger.to_state.state == 'on'
                 and trigger.to_state.context.user_id is not none }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_on_override_flag
          - wait_for_trigger:
              - platform: template
                value_template: "{{ is_state(sensor, 'clear') }}"
          - delay:
              minutes: !input manual_on_minutes
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_on_override_flag
          - stop:

  ###########################################################################
  # 3 — Manual OFF override
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id in lights
                 and trigger.to_state.state == 'off'
                 and trigger.to_state.context.user_id is not none }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_off_override_flag
          - wait_for_trigger:
              - platform: template
                value_template: "{{ is_state(sensor, 'clear') }}"
          - delay:
              minutes: !input manual_off_minutes
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_off_override_flag
          - stop:

  ###########################################################################
  # 4 — Auto ON (blocked by OFF override)
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_state(off_flag, 'off')
                 and trigger.entity_id == sensor
                 and trigger.from_state.state == 'clear'
                 and trigger.to_state.state in active_states }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input target_lights

  ###########################################################################
  # 5 — Auto OFF (blocked by ON override)
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_state(on_flag, 'off')
                 and trigger.entity_id == sensor
                 and trigger.to_state.state == 'clear'
                 and states(sensor) not in active_states }}
        sequence:
          - delay:
              seconds: !input off_delay
          - condition: template
            value_template: "{{ is_state(sensor, 'clear') }}"
          - service: light.turn_off
            target:
              entity_id: !input target_lights

mode: queued
max: 20
