alias: "[System] Update Asymmetric Debounced Presence"
description: "Updates debounced presence helpers for all mmWave sensors"
mode: parallel
trigger:
  - platform: template
    value_template: >-
      {{
        'on' if (
          is_state('sensor.p1_presence_state', 'motion') or
          is_state('sensor.p1_presence_state', 'stationary') or
          is_state('sensor.p2_presence_state', 'motion') or
          is_state('sensor.p2_presence_state', 'stationary') or
          is_state('sensor.p3_presence_state', 'motion') or
          is_state('sensor.p3_presence_state', 'stationary')
        ) else 'off'
      }}
action:
  - choose:
      # --- BEDROOM ---
      - conditions:
          - condition: template
            value_template: >-
              {{
                is_state('sensor.p2_presence_state', 'motion') or
                is_state('sensor.p2_presence_state', 'stationary')
              }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.bedroom_presence_debounced
          - service: persistent_notification.create
            data:
              message: "Bedroom presence detected"
              title: "Debounced Presence Update"

      # --- LIVING ROOM ---
      - conditions:
          - condition: template
            value_template: >-
              {{
                is_state('sensor.p1_presence_state', 'motion') or
                is_state('sensor.p1_presence_state', 'stationary')
              }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.living_presence_debounced
          - service: persistent_notification.create
            data:
              message: "Living room presence detected"
              title: "Debounced Presence Update"

      # --- KITCHEN ---
      - conditions:
          - condition: template
            value_template: >-
              {{
                is_state('sensor.p3_presence_state', 'motion') or
                is_state('sensor.p3_presence_state', 'stationary')
              }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.kitchen_presence_debounced
          - service: persistent_notification.create
            data:
              message: "Kitchen presence detected"
              title: "Debounced Presence Update"

    # --- DEFAULT ACTIONS FOR WHEN NO PRESENCE IS DETECTED ---
    default:
      - parallel:
          - sequence:
              - delay:
                  seconds: 5
              - condition: template
                value_template: >-
                  {{ not (is_state('sensor.p2_presence_state', 'motion') or is_state('sensor.p2_presence_state', 'stationary')) }}
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.bedroom_presence_debounced
              - service: persistent_notification.create
                data:
                  message: "Bedroom presence cleared"
                  title: "Debounced Presence Update"

          - sequence:
              - delay:
                  seconds: 5
              - condition: template
                value_template: >-
                  {{ not (is_state('sensor.p1_presence_state', 'motion') or is_state('sensor.p1_presence_state', 'stationary')) }}
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.living_presence_debounced
              - service: persistent_notification.create
                data:
                  message: "Living room presence cleared"
                  title: "Debounced Presence Update"

          - sequence:
              - delay:
                  seconds: 5
              - condition: template
                value_template: >-
                  {{ not (is_state('sensor.p3_presence_state', 'motion') or is_state('sensor.p3_presence_state', 'stationary')) }}
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.kitchen_presence_debounced
              - service: persistent_notification.create
                data:
                  message: "Kitchen presence cleared"
                  title: "Debounced Presence Update"
