blueprint:
  name: Easy Presence Lights
  description: Control lights based on a presence sensor, with auto-off delay, manual override awareness, and optional disable sensors (think vacation mode, sleep mode...).
  domain: automation
  input:
    presence_sensor:
      name: Presence Sensor
      description: The presence sensor that triggers the lights.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    lights:
      name: Lights (multi-select)
      description: The lights to control.
      selector:
        entity:
          domain: light
          multiple: true
    auto_off_delay:
      name: Auto-Off Delay
      description: The delay before turning off the lights after the presence sensor goes off.
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    sunset_offset:
      name: Sunset Offset
      description: The offset in minutes from sunset to start the automation. Use a negative value to start earlier.
      default: -40
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes
    sunrise_offset:
      name: Sunrise Offset
      description: The offset in minutes from sunrise to end the automation. Use a negative value to end earlier.
      default: 40
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes
    disable_sensors:
      name: Disable Sensors
      description: Optional binary sensors that, when on, will disable the automation. Define a sleep mode sensor, for example. 
      default: []
      selector:
        entity:
          multiple: true
          domain: binary_sensor
    manual_override_on:
      name: Manual Override On
      description: Input boolean to track manual on state. You need to create "Toggle" helpers, either for your whole home or separate ones for each room. Cannot be the same as "off" helper!
      selector:
        entity:
          domain: input_boolean
    manual_override_off:
      name: Manual Override Off
      description: Input boolean to track manual off state. ou need to create "Toggle" helpers, either for your whole home or separate ones for each room. Cannot be the same as "on" helper!
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: state
    entity_id: !input presence_sensor
  - platform: state
    entity_id: !input lights

condition:
  - condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: !input sunset_offset
      - condition: sun
        before: sunrise
        before_offset: !input sunrise_offset
  - condition: state
    entity_id: !input disable_sensors
    state: 'off'
    for: 00:00:01
    alias: "Disable Sensors Off"
  - condition: state
    entity_id: !input manual_override_on
    state: 'off'
  - condition: state
    entity_id: !input manual_override_off
    state: 'off'

action:
  - variables:
      sensor: !input presence_sensor
      lights: !input lights
      off_delay: !input auto_off_delay
      on_flag: !input manual_override_on
      off_flag: !input manual_override_off
      active_states: ["on"]

  ###########################################################################
  # 1 — Optional disable sensor
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ disable_sensors | length > 0 and (disable_sensors | select('is_state', 'on') | list | length > 0) }}
        sequence:
          - stop:

  ###########################################################################
  # 2 — Manual ON override
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id in lights
                 and trigger.to_state.state == 'on'
                 and trigger.to_state.context.user_id is not none }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_override_on
          - wait_for_trigger:
              - platform: state
                entity_id: !input presence_sensor
                to: 'off'
          - delay:
              minutes: 5
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_override_on
          - stop:

  ###########################################################################
  # 3 — Manual OFF override
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.entity_id in lights
                 and trigger.to_state.state == 'off'
                 and trigger.to_state.context.user_id is not none }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input manual_override_off
          - wait_for_trigger:
              - platform: state
                entity_id: !input presence_sensor
                to: 'on'
          - delay:
              minutes: 10
          - service: input_boolean.turn_off
            target:
              entity_id: !input manual_override_off
          - stop:

  ###########################################################################
  # 4 — Auto ON (blocked by OFF override)
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_state(off_flag, 'off')
                 and trigger.entity_id == sensor
                 and trigger.to_state.state in active_states }}
        sequence:
          - repeat:
              for_each: !input lights
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"

  ###########################################################################
  # 5 — Auto OFF (blocked by ON override)
  ###########################################################################
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_state(on_flag, 'off')
                 and trigger.entity_id == sensor
                 and trigger.to_state.state == 'off' }}
        sequence:
          - delay:
              seconds: !input auto_off_delay
          - repeat:
              for_each: !input lights
              sequence:
                - service: light.turn_off
                  target:
                    entity_id: "{{ repeat.item }}"

mode: queued
max: 20
